version: '3.7'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     ports:
       - "3306:3306"
     restart: always
     deploy:
       resources:
         limits:  
           memory: 150M
         reservations:
           memory: 140M
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - app_data:/var/www/html
     ports:
       - "80:80"
     restart: always
     deploy:
       resources:
         limits:  
           memory: 100M
         reservations:
           memory: 50M
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
volumes:
    db_data:
    app_data:
